### ISSUE TITLE
How to register a new identity ?

### ISSUE THREAD

**Issue by warlof** [warlof/seat-connector#12]
I actually have this issue as well and it's broken teamspeak by way of SeAT. No one can get beyond it.
<img width="984" alt="Screen Shot 2019-08-21 at 3 21 05 PM" src="https://user-images.githubusercontent.com/48392830/63472576-765bb100-c427-11e9-9948-7e8193626f81.png">

There's a secondary issue in that the identity box only shows up for me, the administrator. the tab shows up for everyone but the teamspeak box isn't there. I'm not clear how to resolve the "unregistered" issue as well. Perhaps this is a byproduct of not being able to pass the password field.

The teamspeak box in the screen cap below only shows up for me. not any of the other authorized users.

<img width="521" alt="Screen Shot 2019-08-21 at 3 21 20 PM" src="https://user-images.githubusercontent.com/48392830/63472581-7a87ce80-c427-11e9-959e-443187a34e66.png">

_Originally posted by @sgeine in https://github.com/warlof/seat-connector/issues/10#issuecomment-523672601_

**Comment by warlof** [comment]
Please read issue carefully @sgeine before replying to them. Original one wasn't related at all with your questions. 

To get access to `identities` you need to have `seat-connector.view` permission
Identities isn't a setup page but a registration one. 

This mean, as a new user, if you want to get your teamspeak access, you need to go on this page and click on the registration button located bellow the teamspeak card.

Doing that will start a registration process, triggering the blue modal from your screen.
Instructions never ask you to actually fill the form, but only provide you information to beeing able to join the teamspeak server. Once done'it's asking you to clic on the green `Confirm` button. This will trigger a new process where SeAT will search for you're user and bind your account.

**Comment by sgeine** [comment]
I mentioned 3, actually. I figured it would be quicker to not make multiple tickets. The first one appears to be the same RE: the password screen.

RE: the registration, all users have seat connector permissions. I simulated some users and it appears the one who was reporting the issue was incorrect. I can see it fine. So please disregard the last two. however, the "server password" which appears similar or the same to the other thread remains the same. Thanks again!

**Comment by sgeine** [comment]
Here's what happens. I click on the person simulated > go to connector > identities > join server (I don't have "register", only "join server"). I am presented with a password screen. There's no server password so I click save then receive this message. clicking close just takes it back. I included relevant screen caps below so you can see the permissions. Hope this helps and thanks again!
<img width="848" alt="Screen Shot 2019-08-22 at 5 58 06 PM" src="https://user-images.githubusercontent.com/48392830/63559442-6c5caf80-c506-11e9-9972-19d0463b4ef0.png">

here are the permissions for the user I simulated and what that role has access to.

<img width="823" alt="Screen Shot 2019-08-22 at 6 02 01 PM" src="https://user-images.githubusercontent.com/48392830/63559559-1b00f000-c507-11e9-87f0-44cecee4f23e.png">
<img width="267" alt="Screen Shot 2019-08-22 at 6 02 24 PM" src="https://user-images.githubusercontent.com/48392830/63559581-3966eb80-c507-11e9-8451-5638193f753a.png">

How it used to use prior was it would prepend their main's name with their corp CORP | Pilot Name. But I don't know if this is still the case as I haven't gotten past the server password yet :)

**Comment by warlof** [comment]
@sgeine during the teamspeak registration flow, the blue modal is providing you a few information like :
 - the server to join with both address/domain and port
 - the optional server password - if any has been set
 - the requested username

getting this error message used to mean you may have join the server, but no user has been found with the nickname he asked you to use.

**Comment by sgeine** [comment]
@warlof :) it means either that or something is broken. The user exists in SeAT. There is no server password either. SeAT does successfully update the server groups from TeamSpeak so TeamSpeak to SeAT communication appears to work.

One thing that isn’t great is that there is no mechanism for internal/external host information in this connector. For example, SeAT and TeamSpeak are both hosted on the same server but the server itself is behind NAT. However, I cannot put localhost in this field because the connector uses the host name field for two things:
1. SeAT > TeamSpeak connectivity
2. The url given to the end user to connect to.

This shouldn’t be the case as it is creates a serious security issue and is inflexible. They should be separate. One hostname for TeamSpeak <> seat connectivity and another hostname to provide to external users. One has to look no further than the suggested SeAT cluster configuration to understand why. What if you create a seat cluster on the same private IP subnet as your TeamSpeak server and TeamSpeak isn’t local? The right thing to do is firewall the server query port from external traffic and only allow it on the private range. You can’t do that with this connector. Instead, you have to put the external hostname in there and open up the server query port to the internet. This is a big security issue that can be easily fixed with 2 fields:
1. Hostname/IP to be given to clients
2. Hostname/IP seat uses to connect to TeamSpeak.

Anyway, the user exists. So assuming the user exists in SeAT and I still get this error message then what would you suggest? Again SeAT is correctly pulling the TeamSpeak roles from TeamSpeak.

**Comment by warlof** [comment]
Using an internal and a public address is technically doable and not a big deal.

Regarding your issue, while I was talking about user, I was talking about teamspeak client. Of course you have a SeAT user. Otherwise you'll not getting access to that page 😜

How many identities with the requested name do you have on the server?

**Comment by sgeine** [comment]
@warlof on the seat server? I  have 1 with that name, that's actually the admin user in the example. I don't have any users defined locally on the team speak server if that's what you're asking. my assumption is that how this works is they click on the link, teamspeak checks if they have an acceptable role/group, assigns it to them on join. I tried it with both the seat admin and a regular line member from seat. every module in seat is current as of this writing :)

**Comment by warlof** [comment]
I'm still talking about teamspeak.

If you're going on your Teamspeak Client, connected to the linked Teamspeak Server and go into `Permissions` followed by `List All Clients`; then searching in the search bar the exact Teamspeak Username SeAT is requesting you to have, how many rows are returned in the list ?

**Comment by sgeine** [comment]
For the example line member I tested he has 1 entry

**Comment by warlof** [comment]
@sgeine do you still have issue with the teamspeak driver 4.1.1?
