### ISSUE TITLE
Discord: 404 USER NOT FOUND || Teamspeak: User not found

### ISSUE THREAD

**Issue by jediefe** [warlof/seat-connector#28]
**Problem:** This issue is about a use case that appeared on my instance. If a user removes himself (or gets removed) from a discord server and then re-registers again by updating their binding, the `revokeOldIdentity` call fails as the API returns `404 USER NOT FOUND`. This blocks the update function. It also blocks the `Remove` function in the connector frontend. 

**Solution:** The 404 error needs to be catched on `sendCall` in `revokeOldIdentity` in `vendor/warlof/seat-discord-connector/src/Http/Controllers/RegistrationController.php`

The same problem occurs for Teamspeak if a user is not listed in the database anymore. The error comes from the query call and needs to be catched, too. This is easier as in the driver, in `revokeOldIdentity` there just needs to be a test if `$user == null`. 

Disclaimer: I do not have the slightest clue why the users weren't listed in the respective databases anymore as this should have been the case...

**Comment by warlof** [comment]
Hi @jediefe 

It seems you already largely investigate the issue and found solution.
Could it be possible for you to suggest a change ? :)

I really apology to bump this ticket only now, but the small availability I have is actually spend in core, unfortunately ^^'

**Comment by jediefe** [comment]
Hi warlof, 

no problem, I can clone the repo, patch the bug and send you a PR (once I found out how :smile: ) . I don't have spare time right now but holiday is approaching, so I will be able to do so soon. Also gonna spend some time on testing v4 then ;-) 

Thanks for coming back at me.

**Comment by warlof** [comment]
Since I started my own and core upgrade tend to the end, I spend a few time to upgrade connector to the new User architecture.

By the meantime, I think about this issue and rework a little bit error management. New version is throwing more exception and they are direct descendant of DriverException which allow both custom Exception implementation and short catching stack.

As a result, I also introduce the `InvalidDriverIdentityException` which can be throw if the requested User is not found.

For Discord point of view, this result in
```
404 Not Found response: {"message": "Unknown Member", "code": 10007}"
```

Finally, I updated the Registration controller from Discord driver according to your proposal.

----

If you can take  a few minutes for a review and return feedback, I would appreciate.

- https://github.com/warlof/seat-connector/compare/bdfc0d7d...17c04540
- https://github.com/warlof/seat-discord-connector/compare/a1944921d17d7931e6647f26ba0986e92381002c...0be818cc00d183bf50cb089ce67e86813f93cba3

**Comment by jediefe** [comment]
Looks good to me. If I understand correctly an identity / user mapping gets revoked on SeAT also in case the respective Discord user can't be found anymore on the Discord server?

**Comment by warlof** [comment]
by manual input, yes.

However, it's detailed in connector logs in all case.
